services:
  extractor:
    build: .
    network_mode: "host"
    environment:
      - RPC_URL=${RPC_URL}

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alerts.rules.yml:/etc/prometheus/alerts.rules.yml
    network_mode: "host"

  alertmanager:
    image: prom/alertmanager:latest
    env_file:
      - .env
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--config.expand-env'
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    network_mode: "host"

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    network_mode: "host"