route:
  receiver: 'telegram_alert'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
  - name: 'telegram_alert'
    telegram_configs:
      - bot_token: '8548757104:AAH7bzVSZqJYlVsvlxf1zX1vlggIkkVfuuY'
        chat_id: 1784757653
        parse_mode: 'HTML'
        message: |-
          🚨 <b>{{ .GroupLabels.alertname }}</b> 🚨
          {{ range .Alerts }}
          <b>Severity:</b> {{ .Labels.severity }}
          <b>Summary:</b> {{ .Annotations.summary }}
          <b>Description:</b> {{ .Annotations.description }}
          {{ end }}